export const types = {
	ACTION_OPEN_EVENT: 'ACTION_OPEN_EVENT',

  ACTION_NEW_SEARCH: 'ACTION_NEW_SEARCH',
	ACTION_SEARCHING_EVENTS: 'ACTION_SEARCHING_EVENTS',
	ACTION_SEARCHED_EVENTS: 'ACTION_SEARCHED_EVENTS',

  ACTION_LOADING_EVENTS: 'ACTION_LOADING_EVENTS',
	ACTION_LOADED_EVENTS: 'ACTION_LOADED_EVENTS',

	ACTION_LOAD_FAVORITES: 'ACTION_LOAD_FAVORITES',
	ACTION_ADD_FAVORITE: 'ACTION_ADD_FAVORITE',
	ACTION_REMOVE_FAVORITE: 'ACTION_REMOVE_FAVORITE',
}